import d01 from '../../svg/weatherIcons/01d.svg';
import d02 from '../../svg/weatherIcons/02d.svg';
import d03 from '../../svg/weatherIcons/03d.svg';
import d04 from '../../svg/weatherIcons/04d.svg';
import d09 from '../../svg/weatherIcons/09d.svg';
import d10 from '../../svg/weatherIcons/10d.svg';
import d11 from '../../svg/weatherIcons/11d.svg';
import d13 from '../../svg/weatherIcons/13d.svg';
import d50 from '../../svg/weatherIcons/50d.svg';
import n01 from '../../svg/weatherIcons/01n.svg';
import n02 from '../../svg/weatherIcons/02n.svg';
import n03 from '../../svg/weatherIcons/03n.svg';
import n04 from '../../svg/weatherIcons/04n.svg';
import n09 from '../../svg/weatherIcons/09n.svg';
import n10 from '../../svg/weatherIcons/10n.svg';
import n11 from '../../svg/weatherIcons/11n.svg';
import n13 from '../../svg/weatherIcons/13n.svg';
import n50 from '../../svg/weatherIcons/50n.svg';

export const currentWeatherSvg = (icon) => {
    if (icon === '01d') return d01;
    else if (icon === '02d') return d02;
    else if (icon === '03d') return d03;
    else if (icon === '04d') return d04;
    else if (icon === '09d') return d09;
    else if (icon === '10d') return d10;
    else if (icon === '11d') return d11;
    else if (icon === '13d') return d13;
    else if (icon === '50d') return d50;
    else if (icon === '01n') return n01;
    else if (icon === '02n') return n02;
    else if (icon === '03n') return n03;
    else if (icon === '04n') return n04;
    else if (icon === '09n') return n09;
    else if (icon === '10n') return n10;
    else if (icon === '11n') return n11;
    else if (icon === '13n') return n13;
    else if (icon === '50n') return n50;
};
